name: Merge into main branch

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  test-and-merge:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout client repository
        uses: actions/checkout@v3
        
      - name: Check last commit for #stable
        id: check_commit
        run: |
          if git log -1 --pretty=%B | grep "#stable"; then
            echo "STABLE_COMMIT=true" >> "$GITHUB_OUTPUT"
            CN=$(git log -1 --pretty=%B | grep "#stable")
            echo "STABLE_COMMIT_NAME=${CN}" >> "$GITHUB_OUTPUT"
          else
            echo "STABLE_COMMIT=false" >> "$GITHUB_OUTPUT"
            echo "Not a stable commit. Exiting."
          fi
          
      - name: Use Node.js 21
        if: ${{ steps.check_commit.outputs.STABLE_COMMIT == 'true' }}
        uses: actions/setup-node@v4
        with:
          node-version: 21.x
          cache: 'npm'
        
      # - name: Install dependencies
      #   if: ${{ steps.check_commit.outputs.STABLE_COMMIT == 'true' }}
      #   run: npm install

      # - name: Run tests
      #   if: ${{ steps.check_commit.outputs.STABLE_COMMIT == 'true' }}
      #   run: npm run test

      - name: Sync development branch
        if: ${{ success() && steps.check_commit.outputs.STABLE_COMMIT == 'true' }}
        uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          source_ref: 'main'
          target_branch: 'development'
          commit_message_template: 'Synchronizing {target_branch} branch before merging into {source_ref}'
          
      - name: Merge development to main
        if: ${{ success() && steps.check_commit.outputs.STABLE_COMMIT == 'true' }}
        uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          source_ref: 'development'
          target_branch: 'main'
          commit_message_template: 'Merge {source_ref} into {target_branch} by an stable commit: ${{ steps.check_commit.outputs.STABLE_COMMIT_NAME }}'
